ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM qts_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM qts_app;

REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM qts_app;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM qts_app;
REVOKE USAGE ON SCHEMA public FROM qts_app;

DO $$
BEGIN
  EXECUTE format('REVOKE CONNECT ON DATABASE %I FROM qts_app', current_database());
END;
$$;
